services:
  # The Message Broker
  redis:
    image: redis:7-alpine
    container_name: buglens_redis
    ports:
      - "6379:6379"

  # The FastAPI Gateway
  api:
    build: .
    container_name: buglens_api
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:////app/data/buglens.db
      - YOLO_CONFIG_DIR=/app
    depends_on:
      - redis
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  # The ML Worker (Runs Engines)
  worker:
    build: .
    container_name: buglens_worker
    volumes:
      - ./data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:////app/data/buglens.db
      - YOLO_CONFIG_DIR=/app
    depends_on:
      - redis
    command: celery -A src.worker.celery_app worker --loglevel=info --concurrency=1

    # UI
  ui:
    build: .
    depends_on:
      - api
    container_name: buglens_ui
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    command: streamlit run src/ui/dashboard.py --server.port 8501 --server.address 0.0.0.0
