services:
  # The Message Broker
  redis:
    image: redis:7-alpine
    container_name: buglens_redis
    ports:
      - "6379:6379"

  # The FastAPI Gateway
  api:
    build: .
    container_name: buglens_api
    volumes:
      - ./data:/app/data
      - ./buglens.db:/app/buglens.db
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - YOLO_CONFIG_DIR=/tmp
    depends_on:
      - redis
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  # The ML Worker (Runs Engines)
  worker:
    build: .
    container_name: buglens_worker
    volumes:
      - ./data:/app/data
      - ./buglens.db:/app/buglens.db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - YOLO_CONFIG_DIR=/tmp
    depends_on:
      - redis
    # Starts the Celery worker
    command: celery -A src.worker.celery_app worker --loglevel=info --concurrency=1